# in production this should probably be busybox, but let's use ubuntu for a
# fair comparison 
FROM ubuntu


MAINTAINER Christian

RUN apt-get update
RUN apt-get install numactl -y

ADD bin /
CMD numactl --physcpubind=0-7,16-23 --localalloc /runme_xeon64
